name: build-only

on:
  push:
    branches-ignore: ['main']

env:
  FREERADIUS_REPOSITORY: https://github.com/FreeRADIUS/freeradius-server.git
  IMAGE_NAME: ${{ github.repository }}
  REGISTRY: ghcr.io
  VERSION: 3.2.7

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set FREERADIUS_RELEASE environment variable
        run: echo "FREERADIUS_RELEASE=release_${VERSION//./_}" >> $GITHUB_ENV

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          build-args: |
            FREERADIUS_REPOSITORY=${{ env.FREERADIUS_REPOSITORY }}
            FREERADIUS_RELEASE=${{ env.FREERADIUS_RELEASE }}
          platforms: linux/arm64
          push: false
          tags: |
            ghcr.io/${{ env.IMAGE_NAME }}:${{ env.VERSION }}
            ghcr.io/${{ env.IMAGE_NAME }}:latest
          labels: ${{ steps.meta.outputs.labels }}
